#pragma once

#define MIN_HEX_ENTITY_SPAWN_DISTANCE 3
#define NUMBER_OF_HEX_ENTITIES 5
#define SCORE_INCREMENT_PER_CAPTURE 2

#define DEFAULT_TABLE_SIZE 10

#define DEFAULT_CURSOR_X 0
#define DEFAULT_CURSOR_Y 0